### ISSUE TITLE
Smooth frequencies in acs monit

### ISSUE THREAD

**Issue by Camerooooon** [JakeRoggenbuck/auto-clock-speed#100]
Frequencies tend to jump around a lot. You can see this clearly by setting the delay to a low number.
We can mitigate this by averaging the past few ticks. The amount we average by could be controlled with a --smoothing flag.

**Comment by JakeRoggenbuck** [comment]
yes!

**Comment by Camerooooon** [comment]
I implemented this and it didn't make reading the temperature/frequencies any easier. Honestly I believe it is no longer a necessary feature.

**Comment by JakeRoggenbuck** [comment]
Alright, thanks for testing it out.

**Comment by Camerooooon** [comment]
For future reference, my implementation can be found [here](https://github.com/Camerooooon/clockspeed/tree/smooth-monit)
