### ISSUE TITLE
We need backup strings for power supply locations

### ISSUE THREAD

**Issue by Camerooooon** [JakeRoggenbuck/auto-clock-speed#112]
Some kernels store power supply status in `/sys/class/power_supply/AC/online` and others store it in `/sys/class/power_supply/AC0/online`. We need to check both, same for batteries.

For checking status of AC we need to check
`/sys/class/power_supply/AC0/online`
`/sys/class/power_supply/AC/online`
`/sys/class/power_supply/AC1/online`

For checking battery status we need to check
`/sys/class/power_supply/BAT0/`
`/sys/class/power_supply/BAT/`
`/sys/class/power_supply/BAT1/`

**Comment by Camerooooon** [comment]
Oh yeah same with ACPI (laptop lid) status

**Comment by Shuzhengz** [comment]
Do u know if it's different in amd systems? Cuz apparently (if I remember correctly) the power status doesn't work on Milo's laptop, which has a Ryzen 7

**Comment by Camerooooon** [comment]
> Do u know if it's different in amd systems? Cuz apparently (if I remember correctly) the power status doesn't work on Milo's laptop, which has a Ryzen 7

Probably because of kernel versions. How about whenever anyone gets a chance we send our kernel versions, CPU type and our directories for battery, ac and acpi..

**Comment by Shuzhengz** [comment]
Yee

**Comment by Camerooooon** [comment]
Laptop \#1 Razer Blade 6.06 running Manjaro Linux
CPU `Intel i7-7700HQ`
Kernel `5.10.42-1-MANJARO`
AC `/sys/class/power_supply/AC0`
BAT `/sys/class/power_supply/BAT0`
ACPI `/proc/acpi/button/lid/LID0/state`
Laptop \#2 Dell XPS 15 Running Arch Linux
CPU `Intel i7-8550U`
Kernel `5.15.10-arch1-1`
AC `/sys/class/power_supply/AC/`
BAT `/sys/class/power_supply/BAT0/`
ACPI `/proc/acpi/button/lid/LID0/state`

**Comment by Shuzhengz** [comment]
Thinkpad X1 Extreme running Fedora Linux 35
CPU `Intel i9-8950HK`
Kernel `5.12.7-300.fc34.x86_64`
AC `/sys/class/power_supply/AC`
BAT `/sys/class/power_supply/BAT0/`
ACPI `/proc/acpi/button/lid/LID/state`

**Comment by JakeRoggenbuck** [comment]
Dell Latitude 7480 running Arch
CPU `Intel i5-7300U`
Kernel `5.14.16-arch1-1`
AC `/sys/class/power_supply/AC/`
BAT `/sys/class/power_supply/BAT0/`
ACPI `/proc/acpi/button/lid/LID0/state`

**Comment by JakeRoggenbuck** [comment]
Made this in case we want to ask others to check their cpu stuff https://gist.github.com/JakeRoggenbuck/2f98ad58d0c73ca341b03250787d8845

**Comment by Shuzhengz** [comment]
Maybe we should send a message upon error for the user to submit their paths and computer models

**Comment by JakeRoggenbuck** [comment]
Yea, i like that idea

**Comment by mileskerr** [comment]
HP omen 15 running arch
CPU: `AMD Ryzen 7 5800H`
Kernel: `5.15.12-arch1-1`
BAT: `/sys/class/power_supply/BAT0`
AC: `/sys/class/power_supply/ACAD/online`
acpi: `/proc/acpi/button/lid/LID/state`

**Comment by Shuzhengz** [comment]
oo @JakeRoggenbuck we need to add ACAD

**Comment by mileskerr** [comment]
also keep in mind there are systems with multiple batteries

**Comment by Shuzhengz** [comment]
Yea but we don't have a living example so we can't rly do anything bout it

**Comment by JakeRoggenbuck** [comment]
We should build a massive laptop with two batteries, like just a thinkpad t-420 with two

**Comment by JakeRoggenbuck** [comment]
Can we 3D print parts of the case?

**Comment by Shuzhengz** [comment]
Oh wait my mom's computer has 2 batteries

**Comment by Shuzhengz** [comment]
She wouldn't let me install Linux tho 😢

**Comment by JakeRoggenbuck** [comment]
oof, maybe use a live boot without install lol

**Comment by Camerooooon** [comment]
I'm going to fix the issue with the AC0 AC1 and AC stuff and we can fix multiple batteries later.

**Comment by JakeRoggenbuck** [comment]
> I'm going to fix the issue with the AC0 AC1 and AC stuff and we can fix multiple batteries later.

Awesome, thanks!
