### ISSUE TITLE
acs run and monitor mode look different

### ISSUE THREAD

**Issue by JakeRoggenbuck** [JakeRoggenbuck/auto-clock-speed#119]

**Comment by JakeRoggenbuck** [comment]
I think I fixed this with #128

**Comment by Shuzhengz** [comment]
this is the run mode for me btw
![image](https://user-images.githubusercontent.com/43869232/149644087-d1b536de-751e-4e06-ad0d-8385f7b48000.png)

**Comment by JakeRoggenbuck** [comment]
It looks like when acs is run on a tower without a battery, it gets forced into monitor mode. It has an extra line and looks like this.
![image](https://user-images.githubusercontent.com/35516367/150426154-f25bc338-8ad8-489d-93d5-cb78fa036b1f.png)

**Comment by JakeRoggenbuck** [comment]
This is fixed now

**Comment by JakeRoggenbuck** [comment]
This is one of the funny issues that keeps reappearing and disappearing

**Comment by JakeRoggenbuck** [comment]
We should do integration testing at some point to check all of this
