### ISSUE TITLE
Power save on overheat

### ISSUE THREAD

**Issue by Camerooooon** [JakeRoggenbuck/auto-clock-speed#122]
Set the specific core to power save when it is above say 90c.

**Comment by Shuzhengz** [comment]
I don't actually know if we want to mess with that, if we mess up on managing the clockspeed (for example making it too fast for a few milliseconds under high load and temp) we could potentially kill a CPU

**Comment by Camerooooon** [comment]
> I don't actually know if we want to mess with that, if we mess up on managing the clockspeed (for example making it too fast for a few milliseconds under high load and temp) we could potentially kill a CPU

Modern cpus and mobos have bios failsafes. Also powersafe governor is managed by Linux so it shouldn't overhead the cpu. Finally the cpu speed program that we're basing acs off of had the same feature (that's how I got the idea)

**Comment by JakeRoggenbuck** [comment]
Hm, might be interesting, should we try to kill a cpu for edge testing? If nothing else will slow down a cpu on overheat, it might be worth building in a heatsafe mode or a flag that can be turned on to enable just a slowdown of some sort.

**Comment by Shuzhengz** [comment]
> > I don't actually know if we want to mess with that, if we mess up on managing the clockspeed (for example making it too fast for a few milliseconds under high load and temp) we could potentially kill a CPU
> 
> Modern cpus and mobos have bios failsafes. Also powersafe governor is managed by Linux so it shouldn't overhead the cpu. Finally the cpu speed program that we're basing acs off of had the same feature (that's how I got the idea)

Yeah but linux could override the bios thermal tip point. If we are going to do this we gotta be careful not to kill anyones cpu (also need to test on more systems)

**Comment by JakeRoggenbuck** [comment]
yee, i agree

**Comment by Shuzhengz** [comment]
> Hm, might be interesting, should we try to kill a cpu for edge testing? If nothing else will slow down a cpu on overheat, it might be worth building in a heatsafe mode or a flag that can be turned on to enable just a slowdown of some sort.

linux should have a limit set at 95C - 99C, but sometimes that can break on some installs
maybe we should have a feature to let the user define what the temp limit should be (for hot environment or if they dont want their fans to run too hot, also need to compare it with the bios limit because some cpus can have different operating temp, and not all linux users use modern cpus)

**Comment by JakeRoggenbuck** [comment]
Yea, we can have a value in the config for "never heat above" or something. What do you think would be a good default value?

**Comment by Shuzhengz** [comment]
97C from my experience on windows to give it some room and not force shut off (it takes a few milliseconds for clocking down to kick into effect), and also there are areas of the CPU that don’t have temperature sensors so we gotta consider that (mainly just check all the cores’ temperatures and compare them)

**Comment by JakeRoggenbuck** [comment]
Yea, it would be kinda rad to have like a user defined auto shut off, like a computer probably should never be at like 100C for any normal use case. I'm very interested in doing this feature!

**Comment by Shuzhengz** [comment]
> Yea, it would be kinda rad to have like a user defined auto shut off, like a computer probably should never be at like 100C for any normal use case. I'm very interested in doing this feature!

My laptop’s normal operating temperature is actually 95C 😅

**Comment by JakeRoggenbuck** [comment]
oh gosh. I have my house's heater on 
![image](https://user-images.githubusercontent.com/35516367/149268228-51b927cb-7960-441e-b91a-0eac339fa78e.png)

**Comment by Camerooooon** [comment]
Jake do you want to do this or can I?

**Comment by JakeRoggenbuck** [comment]
> Jake do you want to do this or can I?

Go for it!
