### ISSUE TITLE
Inaccurate Temperature On Some Cores

### ISSUE THREAD

**Issue by Shuzhengz** [JakeRoggenbuck/auto-clock-speed#135]
**Describe the bug**
Not sure if it’s something we can fix, but sometimes some core temperatures for high core count systems will show 1C, which isn’t realistic

**To Reproduce**
1. Enable Hyperthreading
2. Run `acs monitor`

**Expected behavior**
2 of the cores (if u have a 12 core CPU like mine) will show 1C temperature

**On Laptop**
Version 0.17
ThinkPad X1 Extreme Gen 1

**Comment by Shuzhengz** [comment]
**Describe the bug**
Half the cores show 0C

**To Reproduce**
Steps to reproduce the behavior:

- Enable Hyperthreading
- Run acs monitor

**Expected behavior**
2 of the cores on the 4 core CPU (Core i7-3520M) will show 0 C

**On Laptop**
Version 0.17
ThinkPad X230
Fedora Server 34

**Comment by Shuzhengz** [comment]
![image](https://user-images.githubusercontent.com/43869232/150261107-2762e8ac-b6e5-4878-9472-08ad96bb7718.png)

**Comment by Shuzhengz** [comment]
also @JakeRoggenbuck do u know what the `schedutil` governor is?

**Comment by JakeRoggenbuck** [comment]
> 

Nope, that's weird

**Comment by JakeRoggenbuck** [comment]
And yea, why 0C? that's definitely a bug

**Comment by Shuzhengz** [comment]
yea

**Comment by Shuzhengz** [comment]
maybe its cuz the temperature for these logical processors (theres only 2 cores, the other 2 are from hyperthreading) are supposed to be derived from their physical counterparts?

**Comment by JakeRoggenbuck** [comment]
Should we say if temp is 0, use temp from other cores?

**Comment by Shuzhengz** [comment]
@JakeRoggenbuck can u check if

`/sys/devices/system/cpu/cpu0/topology/thread_siblings_list`

is a thing on ur computer?

**Comment by Shuzhengz** [comment]
it seems like its a description of which cores are hyperthreaded from real cores

**Comment by Shuzhengz** [comment]
> Should we say if temp is 0, use temp from other cores?

nah, cuz they're logical cores in the first place, so they share the same sensors with the actual cores. As long as we find their actual core we should be good

**Comment by JakeRoggenbuck** [comment]
I am also having this issue now 
![image](https://user-images.githubusercontent.com/35516367/150429453-ed8115ee-2ab9-4c72-9042-1bfb2772ad76.png)

**Comment by JakeRoggenbuck** [comment]
> @JakeRoggenbuck can u check if
> 
> `/sys/devices/system/cpu/cpu0/topology/thread_siblings_list`
> 
> is a thing on ur computer?

yup

**Comment by JakeRoggenbuck** [comment]
![image](https://user-images.githubusercontent.com/35516367/150429583-77e44d2e-1b4a-41b8-908e-a870543069b9.png)

**Comment by Shuzhengz** [comment]
> ![image](https://user-images.githubusercontent.com/35516367/150429583-77e44d2e-1b4a-41b8-908e-a870543069b9.png)
> 
> 

hmm thats not quite right
it should return a list, like `2, 4` so you know which ones are paired

**Comment by JakeRoggenbuck** [comment]
Hm, yea, i'll look into why mine is doing this

**Comment by Shuzhengz** [comment]
hmm maybe change the cpu0 to some other ones?
also do you have hyperthreading enabled?

**Comment by JakeRoggenbuck** [comment]
I'm not sure

**Comment by Shuzhengz** [comment]
U can check in the bios
It should be in the CPU tab

**Comment by JakeRoggenbuck** [comment]
What should we do if we can't get the temp? Should we just not display the value? Could we get the other temps?

**Comment by Shuzhengz** [comment]
maybe we should just list N/A (getting a wrong core temp is kinda bad)

**Comment by Shuzhengz** [comment]
also an idea, maybe we should make an api version of the program

**Comment by JakeRoggenbuck** [comment]
> 

I like this, would it be more like a rust library or something that runs REST and can be called from another app?

**Comment by JakeRoggenbuck** [comment]
Like maybe a web dashboard

**Comment by JakeRoggenbuck** [comment]
Hm, my temps are back to normal 
![image](https://user-images.githubusercontent.com/35516367/151885403-7aff2bce-feb6-4d50-8905-1575d28da562.png)

**Comment by JakeRoggenbuck** [comment]
Do you think if a temp is zero, we could do avg(other_temps)* or something. For example.
```
20C
20C
21C
20C*
```

The last one was not found, but is an average of the other ones, with the * to inform the user that it isn't the real temp, but just the most accurate prediction.

**Comment by Shuzhengz** [comment]
oo that's a good idea
