### ISSUE TITLE
Battery does N/A%

### ISSUE THREAD

**Issue by JakeRoggenbuck** [JakeRoggenbuck/auto-clock-speed#138]
**Describe the bug**
The battery does N/A%

**To Reproduce**
1. Ran command 'acs monit'
2. Specific condition 'Ran on a tower with no battery'
3. See error

**Expected behavior**
Should have done `N/A`

**Screenshots**

![image](https://user-images.githubusercontent.com/35516367/150428940-38acd690-519a-4064-9bb1-a1acb19ffc42.png)

**On Tower**
Version [e.g. 0.1.7]

**Comment by Shuzhengz** [comment]
oo maybe we should have an option to let the user manually select power governor regardless of battery

**Comment by JakeRoggenbuck** [comment]
That would be cool, maybe something in the config

**Comment by Shuzhengz** [comment]
yee

**Comment by Camerooooon** [comment]
When no battery is present make it not have the battery line.

**Comment by JakeRoggenbuck** [comment]
Oh, that's a good idea. `Battery: N/A` vs no battery.
