### ISSUE TITLE
Manual Governor Select

### ISSUE THREAD

**Issue by Shuzhengz** [JakeRoggenbuck/auto-clock-speed#141]
Let the user select the power plan (and possibly modify) manually (to any avaliable governor)

**Comment by JakeRoggenbuck** [comment]
Yee, we have a `acs set gov performance` but I don't know if it will stay like that if it's running on `acs run`

**Comment by JakeRoggenbuck** [comment]
yea, to better state that, doing `acs run` will change the user set default. If `acs run` is not on, then I think the user can just set it.

**Comment by JakeRoggenbuck** [comment]
I'll try to work on this

**Comment by Shuzhengz** [comment]
o i actually already started on this lol

**Comment by JakeRoggenbuck** [comment]
Oh, yee! Yea, you can go for it!

**Comment by Shuzhengz** [comment]
@JakeRoggenbuck okay so i could't figure out how to make `apply_to_cpus()` work on custom governors without making things unsafe, so yeah kinda stuck lol
I did get schedutil working with #290 tho

**Comment by JakeRoggenbuck** [comment]
> @JakeRoggenbuck okay so i could't figure out how to make `apply_to_cpus()` work on custom governors without making things unsafe, so yeah kinda stuck lol I did get schedutil working with #290 tho

Awesome, sounds good!

**Comment by JakeRoggenbuck** [comment]
We could make like a "are you very sure you wanna do this? [y/N]" thingy

**Comment by Shuzhengz** [comment]
yea lol

**Comment by Shuzhengz** [comment]
_press y for your computer to explode_

**Comment by JakeRoggenbuck** [comment]
Was this done in #290?

**Comment by JakeRoggenbuck** [comment]
@Shuzhengz

**Comment by Shuzhengz** [comment]
Sort of, but since we're not gonna do this we should prob close it

**Comment by JakeRoggenbuck** [comment]
Alright, should we have an issue for "Discuss future use of user inputted gov"? Also, we might want to add some of the other govs and stuff that intel has.
