### ISSUE TITLE
Monit and run not shown in systemctl status or journal

### ISSUE THREAD

**Issue by JakeRoggenbuck** [JakeRoggenbuck/auto-clock-speed#151]
**Describe the bug**
Monit and run not shown in systemctl status or journal
![image](https://user-images.githubusercontent.com/35516367/151593606-4a155dd5-0d87-4ee1-8a22-221068a64a13.png)

**To Reproduce**
1. Install current acs
2. Ran command 'systemctl restart acs'
3. See error

**Expected behavior**
It should show
![image](https://user-images.githubusercontent.com/35516367/151593904-c114389f-5a86-4474-b8a5-26e44d96f1f0.png)

**On Laptop**
Version: e3480ed

**Comment by JakeRoggenbuck** [comment]
I think we can make a --no-animation flag for systemctl running

**Comment by Shuzhengz** [comment]
hmm dats weird how the animation breaks it
