### ISSUE TITLE
ACS always in powersave

### ISSUE THREAD

**Issue by Shuzhengz** [JakeRoggenbuck/auto-clock-speed#166]
**Describe the bug**
Something broke and acs is now always in powersave in both run and monitor

**To Reproduce**
1. Ran command 'sudo acs run' or `acs moniotr -g`
2. Specific condition `regardless of situation`
3. See error

**Expected behavior**
ACS in powersave regardless of circumstances

**Screenshots**
![image](https://user-images.githubusercontent.com/43869232/151722694-c92f780f-5096-4114-917c-68896927ac35.png)

**On Laptop**
Version 0.1.7 latest main

**Comment by Shuzhengz** [comment]
heres a screenshot of acs running while building a program's source code
![image](https://user-images.githubusercontent.com/43869232/151722770-a5b6213e-8b47-4af3-8934-8e327676eb81.png)

CPU frequency is at max, but governor is still powersave

**Comment by JakeRoggenbuck** [comment]
What happens when charging?

**Comment by JakeRoggenbuck** [comment]
Maybe you have the old version running on systemctl?

**Comment by Shuzhengz** [comment]
yea lemme check

**Comment by Shuzhengz** [comment]
also some cores disappear in monitor mode
![image](https://user-images.githubusercontent.com/43869232/151723023-4fe76efa-6d0f-4076-b3e8-a8a6f0ef237c.png)

**Comment by Shuzhengz** [comment]
and by some i mean 8 of them

**Comment by JakeRoggenbuck** [comment]
Cool, that looks like the one

**Comment by JakeRoggenbuck** [comment]
Right now it performances when charging

**Comment by JakeRoggenbuck** [comment]
We gotta go back to the flowchart

**Comment by Shuzhengz** [comment]
i solved the problem!
so basically on all systems with SELinux, we need to either disable SELinux (not recommended), or create a new policy group to let acs through
ill create a pr to fix it in a bit

**Comment by Shuzhengz** [comment]
it seems like SELinux is enabled by default in RHEL, Fedora, CentOS, RockyLinux, QubesOS, Debian
Ubuntu and OpenSUSE have it installed but not enabled by default

**Comment by Shuzhengz** [comment]
Raw Audit Message for refrence

`type=AVC msg=audit(1643839448.993:136): avc:  denied  { read open } for  pid=1054 comm="(acs)" path="/home/Zsz/.cargo/bin/acs" dev="nvme1n1p6" ino=2438319 scontext=system_u:system_r:init_t:s0 tcontext=unconfined_u:object_r:user_home_t:s0 tclass=file permissive=0`

**Comment by Shuzhengz** [comment]
To allow access for now:
`# ausearch -c '(acs)' --raw | audit2allow -M my-acs`
`# semodule -X 300 -i my-acs.pp`

**Comment by JakeRoggenbuck** [comment]
Yay! Thanks!!

**Comment by JakeRoggenbuck** [comment]
Should we make a troubleshooting.md to add this to?

**Comment by JakeRoggenbuck** [comment]
Added this to the wiki, feel free to revise https://github.com/JakeRoggenbuck/auto-clock-speed/wiki/Troubleshooting
