### ISSUE TITLE
We check get_best_path() each time functions are called

### ISSUE THREAD

**Issue by JakeRoggenbuck** [JakeRoggenbuck/auto-clock-speed#168]
These functions all call get_best_path every time they are called 
- read_power_source
- read_battery_charge
- read_lid_state

We should do something at the start to determine each path

**Comment by Shuzhengz** [comment]
maybe cache the path?

**Comment by JakeRoggenbuck** [comment]
Yea

**Comment by JakeRoggenbuck** [comment]
Done
