### ISSUE TITLE
ACS adds a lot to /var/log/journal

### ISSUE THREAD

**Issue by JakeRoggenbuck** [JakeRoggenbuck/auto-clock-speed#181]
![image](https://user-images.githubusercontent.com/35516367/152022220-23f1459d-cbf7-43d9-a814-91766d928996.png)

**Comment by JakeRoggenbuck** [comment]
I added --quiet to my acs.service, maybe we should set that to default

**Comment by Camerooooon** [comment]
Yeah that was the purpose of --quiet.

**Comment by JakeRoggenbuck** [comment]
it's like verbose, but the word suggests it is true and showing by default. Instead of asking to be verbose, you ask it to be quiet

**Comment by JakeRoggenbuck** [comment]
It will do the clock management without printing
