### ISSUE TITLE
can't set governor to anything other than powersave and performance

### ISSUE THREAD

**Issue by mileskerr** [JakeRoggenbuck/auto-clock-speed#185]
when running `acs --monitor` after restarting, i get this output
```
Auto Clock Speed daemon has been initialized in monitor mode with a delay of 1000 milliseconds

Name  Max       Min     Freq    Temp    Governor
cpu0: 3200Hz    1200Hz  1196Hz  46C     schedutil
cpu1: 3200Hz    1200Hz  1197Hz  36C     schedutil
cpu10: 3200Hz   1200Hz  2466Hz  0C      schedutil
cpu11: 3200Hz   1200Hz  1196Hz  0C      schedutil
cpu12: 3200Hz   1200Hz  1197Hz  0C      schedutil
cpu13: 3200Hz   1200Hz  1197Hz  0C      schedutil
cpu14: 3200Hz   1200Hz  1365Hz  0C      schedutil
cpu15: 3200Hz   1200Hz  1396Hz  0C      schedutil
cpu2: 3200Hz    1200Hz  1196Hz  0C      schedutil
cpu3: 3200Hz    1200Hz  1197Hz  0C      schedutil
cpu4: 3200Hz    1200Hz  1197Hz  0C      schedutil
cpu5: 3200Hz    1200Hz  1196Hz  0C      schedutil
cpu6: 3200Hz    1200Hz  1197Hz  0C      schedutil
cpu7: 3200Hz    1200Hz  1197Hz  0C      schedutil
cpu8: 3200Hz    1200Hz  1209Hz  0C      schedutil
cpu9: 3200Hz    1200Hz  1197Hz  0C      schedutil

Battery: 99%
Could not check turbo
Something went wrong. Try running with sudo.


ctrl+c to stop running

```

running
`sudo acs set gov powersave`
or
`sudo acs set gov performance`
works as expected and changes the output of `acs monitor`, but it is impossible to change it back to schedutil.

running
`sudo acs set gov schedutil`
gives this error
```
Gov "schedutil" not available
```

i also remember an older version of acs having a list-govs option. I can't find it in the current version and maybe I'm trippin, but I'm pretty sure when this option existed it outputted several other governors besides schedutil, powersave, and performance, non of which acs could actually switch to.

**Comment by JakeRoggenbuck** [comment]
Thanks for the bug report!
Yea, we should add "schedutil" because we don't have that yet.
Maybe try `sudo acs run` because that will edit the govs when running.
I'll look into that tho, thanks!

**Comment by JakeRoggenbuck** [comment]
Oh, and I think we renamed the list to `available-govs`

**Comment by JakeRoggenbuck** [comment]
We should abbreviate that

**Comment by mileskerr** [comment]
there is no list subcommand

**Comment by mileskerr** [comment]
different machines will inevitably have different governors. why not auto-detect the names?

**Comment by JakeRoggenbuck** [comment]
> different machines will inevitably have different governors. why not auto-detect the names?

That's a good question, we want to limit the amount of data the user can input into their system. It might be too powerful for a user provided string to be set `cpufreq/scaling_governor` as super user.

I do think we should add more and limit the use of them only when available.
Here's an idea,

1. Have functions for setting specific govs, e.g. set_powersave().
2. Check if powersave is available on the machine with check_available_governors()
3. Run set_powersave if available on machine

I think this would be a way to have no user input, not let users use actual govs that aren't available, and expand the amount of supported governors. What do y'all think?

**Comment by JakeRoggenbuck** [comment]
Future planning docs:
I do think we should add more and limit the use of them only when available.
Here's an idea,

1. Have functions for setting specific govs, e.g. set_powersave().
2. Check if powersave is available on the machine with check_available_governors()
3. Run set_powersave if available on machine

I think this would be a way to have no user input, not let users use actual govs that aren't available, and expand the amount of supported governors. What do y'all think?
