### ISSUE TITLE
Work on Wiki

### ISSUE THREAD

**Issue by Shuzhengz** [JakeRoggenbuck/auto-clock-speed#190]
Yeah we need to work on the wiki lol

**Comment by JakeRoggenbuck** [comment]
The natural progression of this is,
1. Add all of out content onto the wiki
2. Add notice to README saying where new info will be
3. Remove the some original content from README

**Comment by JakeRoggenbuck** [comment]
What pages should we add? I think there should be a troubleshooting guide for specific problems

**Comment by Shuzhengz** [comment]
yeah i added a known issues page and i think it should be in there

**Comment by JakeRoggenbuck** [comment]
Done with #194
