### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by Shuzhengz** [JakeRoggenbuck/auto-clock-speed#191]
Anyone wanna make a cool icon?

**Comment by JakeRoggenbuck** [comment]
This would be great!!

**Comment by JakeRoggenbuck** [comment]
Suggestion for concept art, posted here rather than where i put it before #189 
![ACS](https://user-images.githubusercontent.com/35516367/152627600-b97869df-5e74-4634-bd93-8b064d5f6746.png)

**Comment by JakeRoggenbuck** [comment]
![ACS rs](https://user-images.githubusercontent.com/35516367/152627611-968b5ef0-a9e3-4c7b-b2a8-52e084be8ac2.png)
