### ISSUE TITLE
Sorting is bad on CPUs over 10 cores

### ISSUE THREAD

**Issue by Shuzhengz** [JakeRoggenbuck/auto-clock-speed#205]
**Describe the bug**
Sorting breaks on CPUs with more than 10 cores

**To Reproduce**
1. Buy a CPU with more than 10 cores
2. Run acs monitor
3. The sorting will be thrown off

**Expected behavior**
see screenshot

**Screen
![s](https://user-images.githubusercontent.com/43869232/152671295-2d567927-4871-4dbe-ac6c-9ce3653db91f.png)
shots**

**On Laptop**
Version 0.1.7

**Comment by JakeRoggenbuck** [comment]
Ohhh, hm, it's doing alphabetical

**Comment by JakeRoggenbuck** [comment]
We just need to change this to work with numeric values https://github.com/JakeRoggenbuck/auto-clock-speed/blob/d8b66d1f327c31acf9c282fba83189b63ca44e91/src/system.rs#L123
