### ISSUE TITLE
First Line Gets Cut Off

### ISSUE THREAD

**Issue by Shuzhengz** [JakeRoggenbuck/auto-clock-speed#212]
**Describe the bug**
The first line gets cut off in monitor and run

**Screenshots**
![image](https://user-images.githubusercontent.com/43869232/152700909-a41d7406-8b30-4560-9279-73acc9039ae4.png)

**On Laptop**
Version 0.1.7

**Comment by Shuzhengz** [comment]
gets cut off in small windows

**Comment by JakeRoggenbuck** [comment]
Hm, does it ever reset? That was the case for me, but it would update again after refresh

**Comment by Shuzhengz** [comment]
No it doesn't reset for me

**Comment by JakeRoggenbuck** [comment]
Lets investigate this. @Shuzhengz Can you try pulling from main and running with `-c`.

**Comment by JakeRoggenbuck** [comment]
What terminal, alacritty?

**Comment by JakeRoggenbuck** [comment]
Because the turbo is off by a line, so i'm thinking this might be an old version? but i might be wrong

**Comment by JakeRoggenbuck** [comment]
when you get a chance, no rush

**Comment by Shuzhengz** [comment]
oh it fixed itself actually
