### ISSUE TITLE
Profiling tool

### ISSUE THREAD

**Issue by Shuzhengz** [JakeRoggenbuck/auto-clock-speed#219]
Maybe we could include a profiling tool that simulates how the program rus and gives feedback for us to optimize it

**Comment by JakeRoggenbuck** [comment]
ohhh, yesss

**Comment by JakeRoggenbuck** [comment]
This sounds really cool, lets brainstorm what we could check

**Comment by JakeRoggenbuck** [comment]
I honestly think we could cache or save values of some functions, like the list_cpus function is probably incredibly expensive, we could probably cache that, or save the value.

**Comment by Shuzhengz** [comment]
yeah, caching is good practice in rust right?

**Comment by JakeRoggenbuck** [comment]
> yeah, caching is good practice in rust right?

Yea, it depends. I think we could just run list cpus at the start and then save the value because it won't change throughout the program

**Comment by Shuzhengz** [comment]
found this, might be useful
https://crates.io/crates/criterion

**Comment by JakeRoggenbuck** [comment]
Using flamegraph now
