### ISSUE TITLE
get-freq shows the last CPU's frequency instead of the average

### ISSUE THREAD

**Issue by Camerooooon** [JakeRoggenbuck/auto-clock-speed#23]
https://cameron.media/u/9f3skJduEY.png

**Comment by JakeRoggenbuck** [comment]
Yea, we probably only need to change comments saying it average. Alternatively, we can get all of them, then actually average them. What do you think?

**Comment by Camerooooon** [comment]
I think we average instead I can do this.

**Comment by JakeRoggenbuck** [comment]
Go for it!

**Comment by JakeRoggenbuck** [comment]
whoops, fixed the assignment

**Comment by JakeRoggenbuck** [comment]
you got this!
