### ISSUE TITLE
Temperatures on some cores do not update

### ISSUE THREAD

**Issue by Shuzhengz** [JakeRoggenbuck/auto-clock-speed#250]
**Describe the bug**
Some temperatures do not update whatever you do on your computer
The temperature the program gets at startup seems to be correct, but some cpu cores do not update after that

**To Reproduce**
1. Ran command 'acs monitor'
2. Specific condition: was plugged in, although that's because my computer does weird stuff when on battery
3. Run something heavy (I used blender to render on CPU)

**Expected behavior**
Some CPU cores shoots up to 90C, as they should, but some other ones stay and do not get updated

**On Laptop**
Version 0.1.8, Fedora R35

**Comment by JakeRoggenbuck** [comment]
I'll look into this some more. Could this be a kernel issue?

**Comment by Shuzhengz** [comment]
> I'll look into this some more. Could this be a kernel issue?

It might be a BIOS/hyperthreading/multithreading issue actually, I've the same fedora install on 3 laptops and only 2 of them have this issue

**Comment by JakeRoggenbuck** [comment]
ah, yea

**Comment by Shuzhengz** [comment]
using msr could get around this, but im stuck on getting it to worl

**Comment by JakeRoggenbuck** [comment]
> using msr could get around this, but im stuck on getting it to worl

:+1:

**Comment by JakeRoggenbuck** [comment]
@Shuzhengz What should we do with this? Should we set non-existent data to the average temp of working cores and add a little warning next to it?

**Comment by Shuzhengz** [comment]
eh i remembered talking about package temp somewhere, so maybe we can use that
but yeah if not we can just use average

**Comment by JakeRoggenbuck** [comment]
okay, sounds good. thanks!
