### ISSUE TITLE
Option to ignore power

### ISSUE THREAD

**Issue by swetoast** [JakeRoggenbuck/auto-clock-speed#253]
Running this software on a Raspberry Pi and i want the option to skip power check cause if i run it as a service it bumps it up to performance since it thinks it is a laptop so if there could be a param in  the config like 

ignore_power=yes

so it can focus on giving a low power raspberry pi the chance to go even lower in power consumption by powersaving and giving it power when its needed.

**Comment by JakeRoggenbuck** [comment]
Yea! That can be done

**Comment by JakeRoggenbuck** [comment]
Thanks for making a feature request, we will get right to making the feature!
