### ISSUE TITLE
Change governor based on cpu usage

### ISSUE THREAD

**Issue by Camerooooon** [JakeRoggenbuck/auto-clock-speed#271]
We should discuss if we should do this.

**Comment by Shuzhengz** [comment]
i think that's the schutil governor, so only on systems without it

**Comment by Camerooooon** [comment]
I'm thinking that we make it switch to performance if cpu usage is >80% for more than 15 seconds. This way we can maintain peak outputs when necessary while still maintaining very good battery life. What do you think @JakeRoggenbuck @Shuzhengz

**Comment by JakeRoggenbuck** [comment]
That's an amazing idea, like hypercharge if the usage is really high for a consistent little bit

**Comment by Shuzhengz** [comment]
yee! although only when battery is above 20% tho

**Comment by Camerooooon** [comment]
> yee! although only when battery is above 20% tho

Good idea
