### ISSUE TITLE
CPU Usage graph

### ISSUE THREAD

**Issue by Camerooooon** [JakeRoggenbuck/auto-clock-speed#285]
acs monit --graph should have an option to graph CPU usage.

**Comment by Shuzhengz** [comment]
maybe just graph clockspeed and usage on the same graph
i mean the max value is already set (unless the user somehow overclocks the laptop CPU)

**Comment by Camerooooon** [comment]
Graphing multiple different things at once might be confusing. I'm thinking about giving the --graph parameter an option for either "usage-single" "usage" "frequency-single" "frequency"

**Comment by Shuzhengz** [comment]
u can just make the two lines different colors

**Comment by JakeRoggenbuck** [comment]
I think a combination would be good. Like these
```sh
acs --graph frequency
# or
acs --graph usage frequency
```

**Comment by JakeRoggenbuck** [comment]
We could have something where you could have one, or both and if you have both we can make the lines different colors
