### ISSUE TITLE
Build fails with glibc 2.35

### ISSUE THREAD

**Issue by Shuzhengz** [JakeRoggenbuck/auto-clock-speed#288]
**Describe the bug**
error: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/zsz/Documents/auto-clock-speed/target/debug/deps/libstructopt_derive-e4816a3f609f3600.so)

Basically `structopt` doesn't work properly

**To Reproduce**
Build the program using the latest glibc

**On Laptop**
Version v0.1.8 devel

**Comment by Shuzhengz** [comment]
not a huge deal since I can roll back, but very annoying

**Comment by JakeRoggenbuck** [comment]
That is weird, do you know why it happens?

**Comment by Shuzhengz** [comment]
I think 2.34 especially is a dependency of structopt, so it won't work with newer releases (2.34 is EOL on newer distros releases, its not even avaliable in the package manager)
