### ISSUE TITLE
Refactor Governor Rules

### ISSUE THREAD

**Issue by Camerooooon** [JakeRoggenbuck/auto-clock-speed#298]
Convert the rules to a "State" enum. 

The state enum contains the current state of the system, some states have priority over others, for example, OVERHEATING would have priority over CPU_USAGE_HIGH. The states would then be updated and applied every cycle. This would simplify the applying of governors because we would only need to detect when the state changes. The states would be controlled by a state machine.

States:
NORMAL,
BATTERY_LOW,
LID_CLOSED,
CPU_USAGE_HIGH,
OVERHEATING

**Comment by Shuzhengz** [comment]
maybe add an unstable battery for old batteries

**Comment by JakeRoggenbuck** [comment]
Closed in #299
