### ISSUE TITLE
Unit tests do not include other govs, only powersave and performance

### ISSUE THREAD

**Issue by JakeRoggenbuck** [JakeRoggenbuck/auto-clock-speed#322]
Unit tests do not include other govs, only powersave and performance

**Comment by JakeRoggenbuck** [comment]
Some tests fail on my AMD Ryzen

**Comment by Shuzhengz** [comment]
> Some tests fail on my AMD Ryzen

Yeah the program also doesn't work 100% with milo's computer

**Comment by Shuzhengz** [comment]
> Unit tests do not include other govs, only powersave and performance

I'm not sure if we want to do schedutil because it's essentially an auto governor that determines the governor for you

**Comment by Shuzhengz** [comment]
also as @Camerooooon said, schedutil will cause some temperature readings to fail, and do some other random stuff

**Comment by JakeRoggenbuck** [comment]
> also as @Camerooooon said, schedutil will cause some temperature readings to fail, and do some other random stuff
Hm, weird
