### ISSUE TITLE
Tests are failing on main!

### ISSUE THREAD

**Issue by Camerooooon** [JakeRoggenbuck/auto-clock-speed#332]
**Describe the bug**
The test system::tests::list_cpus_acs_test is FAILING

**To Reproduce**
Run tests (not in workflows)

**Expected behavior**
The tests should have passed

**Version**
Main

**Comment by Camerooooon** [comment]
From my tests it looks like cpu isn't updating in list_cpus()

**Comment by JakeRoggenbuck** [comment]
Yea, I reverted 7009df08be0 on a local branch and it seemed to have the tests pass.

**Comment by JakeRoggenbuck** [comment]
I kinda did weird things with git tho and I don't think I should push it

**Comment by Camerooooon** [comment]
@JakeRoggenbuck I have fixed this!
