### ISSUE TITLE
Take temperature from thermal zones

### ISSUE THREAD

**Issue by Camerooooon** [JakeRoggenbuck/auto-clock-speed#341]
We should consider thermal zones as an alternative to systems that do not have individual cpu temperature read outs.

**Comment by Shuzhengz** [comment]
yep good idea

**Comment by Camerooooon** [comment]
I would also like to add that thermal zones could also be displayed in addition to regular cpu core temp read outs in acs monit.

**Comment by Shuzhengz** [comment]
im pretty sure most hardware monitoring software have a package temp somewhere, so we could just add it it

**Comment by Camerooooon** [comment]
We should take a look at the source for the "sensors" application. That program was able to read out core temps on my server where auto clock speed otherwise wasn't.

**Comment by Camerooooon** [comment]
> We should take a look at the source for the "sensors" application. That program was able to read out core temps on my server where auto clock speed otherwise wasn't.

I suspect that they use thermal zones in order to achieve this

**Comment by Shuzhengz** [comment]
that would make sense since hyperthreaded cores are not physical

**Comment by Shuzhengz** [comment]
ok i just tested on my other laptop, and turns out that one has 19 thermal zones instead of 2
we need to find the one thats `x86_pkg_temp` type and use the package temperature instead of a bunch of virtual temps

**Comment by Shuzhengz** [comment]
i suspect it's caused by intel vpro

**Comment by Camerooooon** [comment]
> ok i just tested on my other laptop, and turns out that one has 19 thermal zones instead of 2
> 
> we need to find the one thats `x86_pkg_temp` type and use the package temperature instead of a bunch of virtual temps

Are the other thermal zones still useful to us?

**Comment by Camerooooon** [comment]
> ok i just tested on my other laptop, and turns out that one has 19 thermal zones instead of 2
> 
> we need to find the one thats `x86_pkg_temp` type and use the package temperature instead of a bunch of virtual temps

Are the other thermal zones still useful to us?

**Comment by Shuzhengz** [comment]
after running stress test it seems like all the other sensors are virtual and the value of the temperature does not change

**Comment by Shuzhengz** [comment]
after running `cat /sys/class/thermal/thermal_zone*/type` it shows the following
`acpitz
SEN8
SEN9
SENA
SENB
SENC
SEND
pch_cannonlake
B0D4
x86_pkg_temp
iwlwifi_1
INT3400_Thermal
SEN0
SEN1
SEN2
SEN3
SEN4
SEN5
SEN6
SEN7`

**Comment by Shuzhengz** [comment]
it seems like all the `SEN*` types have static value
iwlwifi is probably the dedicated wifi card

**Comment by Shuzhengz** [comment]
the MSR address 0x1b1 also outputs the temperature in hex (you have to convert it into actual readings using the 22:16 output bitfield)

**Comment by Camerooooon** [comment]
Is it alrighty if I take this issue? @Shuzhengz

**Comment by Shuzhengz** [comment]
o yee
