### ISSUE TITLE
Turbo not working on amd

### ISSUE THREAD

**Issue by JakeRoggenbuck** [JakeRoggenbuck/auto-clock-speed#372]
![image](https://user-images.githubusercontent.com/35516367/177015484-47a388dc-5570-4c7d-b71b-76cc04544c71.png)

**Comment by JakeRoggenbuck** [comment]
@Shuzhengz Does amd have turbo?

**Comment by Shuzhengz** [comment]
> @Shuzhengz Does amd have turbo?

yup, its called turbo core though

**Comment by JakeRoggenbuck** [comment]
ohh, hm. so we may need to find the correct path for that

**Comment by Shuzhengz** [comment]
or we can just see if the CPU is going above base clock
turbo literally means the clock speed exceeds base clock

**Comment by JakeRoggenbuck** [comment]
This should just say "Turbo not found" and continue as normal
