### ISSUE TITLE
"Update" model for battery

### ISSUE THREAD

**Issue by Camerooooon** [JakeRoggenbuck/auto-clock-speed#396]

**Comment by JakeRoggenbuck** [comment]
"We should move to an "update" model similar to how we do CPUs where there is a primary update method in Battery that when called sets the value of the data. Then in order to read data from the battery, we just access those variables from the struct."

**Comment by Camerooooon** [comment]
We should move to an "update" model similar to how we do CPUs where there is a primary update method in Battery that when called sets the value of the data. Then in order to read data from the battery, we just access those variables from the struct.
