### ISSUE TITLE
Containers and VMs

### ISSUE THREAD

**Issue by Shuzhengz** [JakeRoggenbuck/auto-clock-speed#430]
Sometimes if the program is running inside a container or VM it cannot see the turbo speed, only the base speed. We should probably tell the user that they’re using the program inside a container so the speed may not be accurate.

**Comment by JakeRoggenbuck** [comment]
Something like "Data from inside virtualization is not representative of the data on the host machine"?

**Comment by Shuzhengz** [comment]
yeah probably

**Comment by Shuzhengz** [comment]
and also idt governor management works in a vm either, so probably have a red text when they run the command to warn them that acs is not intended to run inside vms

**Comment by JakeRoggenbuck** [comment]
> and also idt governor management works in a vm either, so probably have a red text when they run the command to warn them that acs is not intended to run inside vms

Sounds good, yea
