### ISSUE TITLE
Optimize read_lid_state function call

### ISSUE THREAD

**Issue by JakeRoggenbuck** [JakeRoggenbuck/auto-clock-speed#465]
![image](https://user-images.githubusercontent.com/35516367/201425373-16d549f2-5292-4a9a-8ffe-a89b93bfc0a7.png)
In green is just contains function calls for the file.

Here is the code for that.

```rs
fn read_lid_state(&self) -> Result<LidState, Error> {
    if !self.found_path {
        return Ok(LidState::Unapplicable);
    }

    let lid_str = fs::read_to_string(self.best_path)?;

    let state = if lid_str.contains("open") {
        LidState::Open
    } else if lid_str.contains("closed") {
        LidState::Closed
    } else {
        LidState::Unknown
    };
    Ok(state)
}
```

The two contains checks could probably be more optimized with another type of check.

**Comment by Camerooooon** [comment]
We could convert to a prim type and use a match?

**Comment by JakeRoggenbuck** [comment]
> We could convert to a prim type and use a match?

wdym?
