### ISSUE TITLE
Incorrect time

### ISSUE THREAD

**Issue by pibiba** [JakeRoggenbuck/auto-clock-speed#574]
Acs shows incorrect time in log:

```
Auto Clock Speed daemon has been initialized in edit mode with a delay of 1000ms normally and 5000ms when on battery

Name	Max	Min	Freq	Temp	Usage	Governor
cpu0:	3100MHz	1200MHz	1197MHz	52C	8.82%	performance
cpu1:	3100MHz	1200MHz	1198MHz	54C	9.71%	performance
cpu2:	3100MHz	1200MHz	1198MHz	52C	5.10%	performance
cpu3:	3100MHz	1200MHz	1197MHz	52C	8.91%	performance

Battery: 99%
Condition: 45%
Turbo: enabled





ctrl+c to stop running

notice: 2024-10-15 03:57:38 -> State changed: Unknown -> Charging
notice: 2024-10-15 03:57:43 -> State changed: Charging -> Normal
notice: 2024-10-15 03:57:48 -> State changed: Normal -> Charging
```

Output of date and hwclock commands:

```
date        
Tue Oct 15 10:59:09 +07 2024
sudo hwclock --show
2024-10-15 10:59:18.532096+07:00
```

It is possible that acs uses the time set in BIOS, but I can't verify my guess because I use a thinkpad and a modified 1vyrain BIOS, in which date/time settings are [not available](https://medium.com/@n4ru/1vyrain-an-xx30-thinkpad-jailbreak-fd4bb0bdb654):

```
Missing Date & Time in BIOS

This is a side effect of the Advanced Menu needing to go somewhere. You’re not blind. The Date & Time tab is gone. If you really need it, flash a fresh BIOS. You probably don’t though. Setting this in the OS propagates it to the BIOS, in both Windows and (all?) flavors of Linux.
```

**Comment by JakeRoggenbuck** [comment]
Thanks for finding this!

**Comment by pibiba** [comment]
No problem!

It seems that my guess was correct. I checked acs on a device where it is possible to set date/time in BIOS.

```
warn: 2024-10-15 06:33:10 -> Failed to detect a laptop battery
notice: 2024-10-15 06:33:10 -> State changed: Unknown -> BatteryLow
```

The time matches the one set in BIOS
![82bd614f_20241015_133955837_5a65](https://github.com/user-attachments/assets/69f3ca5d-3f1e-4751-b2eb-39237c1200ad)

**Comment by pibiba** [comment]
Look what I [found](https://rust-lang-nursery.github.io/rust-cookbook/development_tools/debugging/config_log.html#include-timestamp-in-log-messages).

```
use std::io::Write;
use chrono::Local;
use env_logger::Builder;
use log::LevelFilter;

fn main() {
    Builder::new()
        .format(|buf, record| {
            writeln!(buf,
                "{} [{}] - {}",
                Local::now().format("%Y-%m-%dT%H:%M:%S"),
                record.level(),
                record.args()
            )
        })
        .filter(None, LevelFilter::Info)
        .init();

    log::warn!("warn");
    log::info!("info");
    log::debug!("debug");
}
```

This program correctly displays the required data even if the system time and the time set in BIOS are different. All that remains is to adapt it for acs :)

The only thing that confuses me is the date output format. Not everyone will find it convenient to use **year/month/day** as well as **day/month/year**. Maybe it's worth adding the `date_format=` parameter to `/etc/acs/acs.toml`, where you can set the preferred option?
