### ISSUE TITLE
Show temp in red if over a value

### ISSUE THREAD

**Issue by JakeRoggenbuck** [JakeRoggenbuck/auto-clock-speed#62]
Maybe 40C would be good

**Comment by Camerooooon** [comment]
Right now my cpu is at 50C with only a web browser open. Might need to be higher or even configurable.

**Comment by JakeRoggenbuck** [comment]
Oh no
![image](https://user-images.githubusercontent.com/35516367/132426602-ee6aafb1-bac1-4676-b9c7-d2be54a28d9e.png)
That's a little warm. I've had to put a laptop in the fridge before.
