### ISSUE TITLE
CPU governors don't get set back to performance when laptop is above 20%

### ISSUE THREAD

**Issue by Camerooooon** [JakeRoggenbuck/auto-clock-speed#74]
This is what I believe the expect behavior to be

If the lid is closed then governors will be set to powersave regardless of charge state
If laptop is plugged in governors will be set to performance
If laptop is bellow 20% governors will be set to powersave unless laptop is charging

Right now it doesn't even bother setting the governors back to performance.

**Comment by JakeRoggenbuck** [comment]
Yea, I agree. We should change it so that it sets it back to performance when it's either plugged in or above a certain value maybe somewhere 50-70%

**Comment by Camerooooon** [comment]
I'll work on this :)

**Comment by Camerooooon** [comment]
This should work now since the battery will only ever charge when plugged in and the laptop is always in performance when plugged in.
